// ─────────────────────────────────────────────────────────────────────────────
// MRKT Campaign System — TypeScript types
// ─────────────────────────────────────────────────────────────────────────────

export type CompensationType =
  | "paid"
  | "gifted"
  | "affiliate"
  | "revenue_share"
  | "unpaid";

export type CampaignStatus =
  | "draft"
  | "active"
  | "paused"
  | "closed"
  | "completed";

export type AssetType =
  | "product_photo"
  | "brand_asset"
  | "campaign_brief"
  | "reference"
  | "brand_guidelines";

// ─────────────────────────────────────────────────────────────────────────────
// Database row types
// ─────────────────────────────────────────────────────────────────────────────

export interface Campaign {
  id: string;
  user_id: string;
  // Business identity (embedded — no separate business_profiles table in V1)
  business_name: string;
  business_industry: string | null;
  business_website: string | null;
  business_instagram: string | null;
  business_tiktok: string | null;
  business_location: string | null;
  // Campaign details
  title: string;
  description: string;
  product_service: string | null;
  campaign_goal: string | null;
  // Compensation — the most important field for creators
  compensation_type: CompensationType;
  compensation_amount_fixed: number | null;
  compensation_budget_min: number | null;
  compensation_budget_max: number | null;
  compensation_per_deliverable: number | null;
  // Creator requirements
  required_niches: string[];
  min_followers: number | null;
  required_country: string | null;
  required_language: string | null;
  required_platforms: string[];
  deadline: string | null;
  // Status
  status: CampaignStatus;
  is_published: boolean;
  created_at: string;
  updated_at: string;
  // Joined relations
  deliverables?: CampaignDeliverable[];
  assets?: CampaignAsset[];
}

export interface CampaignDeliverable {
  id: string;
  campaign_id: string;
  platform: string;
  content_type: string;
  quantity: number;
  notes: string | null;
  display_order: number;
}

export interface CampaignAsset {
  id: string;
  campaign_id: string;
  asset_type: AssetType;
  url: string;
  name: string | null;
  display_order: number;
  created_at: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Campaign creation form state
// ─────────────────────────────────────────────────────────────────────────────

export type PaidStructure = "fixed" | "range" | "per_deliverable";

export interface CampaignFormData {
  // Step 1 — Business Info
  business_name: string;
  business_industry: string;
  business_website: string;
  business_instagram: string;
  business_tiktok: string;
  business_location: string;
  // Step 2 — Campaign Details
  title: string;
  description: string;
  product_service: string;
  campaign_goal: string;
  // Step 3 — Compensation
  compensation_type: CompensationType | null;
  paid_structure: PaidStructure;
  compensation_amount_fixed: string;
  compensation_budget_min: string;
  compensation_budget_max: string;
  compensation_per_deliverable: string;
  // Step 4 — Deliverables
  deliverables: CampaignDeliverableInput[];
  // Step 5 — Requirements + Assets
  required_niches: string[];
  min_followers: string;
  required_country: string;
  required_language: string;
  required_platforms: string[];
  deadline: string;
  assets: CampaignAssetInput[];
}

export interface CampaignDeliverableInput {
  platform: string;
  content_type: string;
  quantity: number;
  notes: string;
}

export interface CampaignAssetInput {
  asset_type: AssetType;
  url: string;
  name: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Display helpers
// ─────────────────────────────────────────────────────────────────────────────

export const COMPENSATION_LABELS: Record<CompensationType, string> = {
  paid:          "Paid",
  gifted:        "Gifted",
  affiliate:     "Affiliate",
  revenue_share: "Revenue Share",
  unpaid:        "Unpaid",
};

export const COMPENSATION_DESCRIPTIONS: Record<CompensationType, string> = {
  paid:          "Fixed fee or budget range paid to creator",
  gifted:        "Free product or service in exchange for content",
  affiliate:     "Commission on sales generated by creator",
  revenue_share: "Percentage of revenue attributed to creator",
  unpaid:        "Content exchange with no monetary compensation",
};

export const ASSET_TYPE_LABELS: Record<AssetType, string> = {
  product_photo:    "Product Photo",
  brand_asset:      "Brand Asset",
  campaign_brief:   "Campaign Brief",
  reference:        "Reference Material",
  brand_guidelines: "Brand Guidelines",
};

export const DELIVERABLE_PLATFORMS = [
  "Instagram",
  "TikTok",
  "YouTube",
  "General",
] as const;

export const DELIVERABLE_TYPES_BY_PLATFORM: Record<string, string[]> = {
  Instagram: ["Reel", "Story", "Post", "Carousel"],
  TikTok:    ["TikTok Video"],
  YouTube:   ["YouTube Short", "Long Video"],
  General:   ["UGC Video", "Photos", "Event Attendance", "Product Review", "Other"],
};

export const INDUSTRY_OPTIONS = [
  "Fashion & Apparel",
  "Beauty & Skincare",
  "Food & Beverage",
  "Health & Fitness",
  "Technology",
  "Travel & Hospitality",
  "Entertainment",
  "Home & Lifestyle",
  "Finance",
  "Education",
  "Retail & E-commerce",
  "Other",
] as const;

export function formatBudget(campaign: Campaign): string {
  const { compensation_type, compensation_amount_fixed, compensation_budget_min, compensation_budget_max, compensation_per_deliverable } = campaign;
  if (compensation_type !== "paid") return COMPENSATION_LABELS[compensation_type];
  if (compensation_amount_fixed) return `$${compensation_amount_fixed.toLocaleString()}`;
  if (compensation_budget_min && compensation_budget_max) return `$${compensation_budget_min.toLocaleString()} – $${compensation_budget_max.toLocaleString()}`;
  if (compensation_budget_min) return `From $${compensation_budget_min.toLocaleString()}`;
  if (compensation_per_deliverable) return `$${compensation_per_deliverable.toLocaleString()} / deliverable`;
  return "Paid";
}

export function compensationColor(type: CompensationType): { text: string; bg: string; border: string } {
  switch (type) {
    case "paid":          return { text: "oklch(0.72 0.14 152)", bg: "oklch(0.72 0.14 152 / 12%)", border: "oklch(0.72 0.14 152 / 30%)" };
    case "gifted":        return { text: "oklch(0.78 0.12 60)",  bg: "oklch(0.78 0.12 60 / 12%)",  border: "oklch(0.78 0.12 60 / 30%)"  };
    case "affiliate":     return { text: "oklch(0.72 0.1 250)",  bg: "oklch(0.72 0.1 250 / 12%)",  border: "oklch(0.72 0.1 250 / 30%)"  };
    case "revenue_share": return { text: "oklch(0.72 0.1 290)",  bg: "oklch(0.72 0.1 290 / 12%)",  border: "oklch(0.72 0.1 290 / 30%)"  };
    case "unpaid":        return { text: "oklch(1 0 0 / 40%)",   bg: "oklch(1 0 0 / 5%)",          border: "oklch(1 0 0 / 12%)"         };
  }
}
